# Generated by Django 5.0.7 on 2024-08-08 10:38

import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0093_uploadedfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.StreamField([('heading', wagtail.blocks.RichTextBlock(form_classname='full title')), ('paragraph', wagtail.blocks.RichTextBlock()), ('button', wagtail.blocks.StructBlock([('text', wagtail.blocks.RichTextBlock(help_text='Enter the button value', required=False)), ('link', wagtail.blocks.URLBlock(help_text='Enter the url of this button', required=False)), ('bg_color', wagtail.blocks.ChoiceBlock(choices=[('darkblue', 'Dark Blue'), ('green', 'Green'), ('white', 'White')], help_text='Choose a button type', required=False))])), ('form_aside', wagtail.blocks.StreamBlock([('heading1', wagtail.blocks.RichTextBlock(help_text='Enter first heading content (big size)', required=False)), ('heading2', wagtail.blocks.RichTextBlock(help_text='Enter second heading content (small size)', required=False)), ('paragraph', wagtail.blocks.RichTextBlock(help_text='Enter paragraph', required=False)), ('contact_form', wagtail.blocks.BooleanBlock(help_text="If it's checked it displays the contact form", required=False)), ('button', wagtail.blocks.StructBlock([('text', wagtail.blocks.RichTextBlock(help_text='Enter the button value', required=False)), ('link', wagtail.blocks.URLBlock(help_text='Enter the url of this button', required=False)), ('bg_color', wagtail.blocks.ChoiceBlock(choices=[('darkblue', 'Dark Blue'), ('green', 'Green'), ('white', 'White')], help_text='Choose a button type', required=False))]))]))], blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
