# Generated by Django 5.0.7 on 2024-08-08 10:58

import wagtail.blocks
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blogpage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='body',
            field=wagtail.fields.StreamField([('heading', wagtail.blocks.RichTextBlock(form_classname='full title')), ('paragraph', wagtail.blocks.RichTextBlock()), ('button', wagtail.blocks.StructBlock([('text', wagtail.blocks.RichTextBlock(help_text='Enter the button value', required=False)), ('link', wagtail.blocks.URLBlock(help_text='Enter the url of this button', required=False)), ('bg_color', wagtail.blocks.ChoiceBlock(choices=[('darkblue', 'Dark Blue'), ('green', 'Green'), ('white', 'White')], help_text='Choose a button type', required=False))])), ('highlight_box', wagtail.blocks.StructBlock([('heading', wagtail.blocks.RichTextBlock(help_text='Enter the heading', required=False)), ('subheading', wagtail.blocks.RichTextBlock(help_text='Enter the subheading', required=False)), ('text', wagtail.blocks.RichTextBlock(help_text='Enter the text', required=False)), ('button', wagtail.blocks.StructBlock([('text', wagtail.blocks.RichTextBlock(help_text='Enter the button value', required=False)), ('link', wagtail.blocks.URLBlock(help_text='Enter the url of this button', required=False)), ('bg_color', wagtail.blocks.ChoiceBlock(choices=[('darkblue', 'Dark Blue'), ('green', 'Green'), ('white', 'White')], help_text='Choose a button type', required=False))], help_text='Enter the button', required=False)), ('contact_us', wagtail.blocks.BooleanBlock(help_text='Check if you want to show contact us button', required=False)), ('bg_color', wagtail.blocks.ChoiceBlock(choices=[('darkblue', 'Dark Blue'), ('green', 'Green'), ('white', 'White'), ('gray', 'Gray')], required=False))])), ('form_aside', wagtail.blocks.StreamBlock([('heading1', wagtail.blocks.RichTextBlock(help_text='Enter first heading content (big size)', required=False)), ('heading2', wagtail.blocks.RichTextBlock(help_text='Enter second heading content (small size)', required=False)), ('paragraph', wagtail.blocks.RichTextBlock(help_text='Enter paragraph', required=False)), ('contact_form', wagtail.blocks.BooleanBlock(help_text="If it's checked it displays the contact form", required=False)), ('button', wagtail.blocks.StructBlock([('text', wagtail.blocks.RichTextBlock(help_text='Enter the button value', required=False)), ('link', wagtail.blocks.URLBlock(help_text='Enter the url of this button', required=False)), ('bg_color', wagtail.blocks.ChoiceBlock(choices=[('darkblue', 'Dark Blue'), ('green', 'Green'), ('white', 'White')], help_text='Choose a button type', required=False))]))])), ('contact_us', wagtail.blocks.StructBlock([('heading', wagtail.blocks.RichTextBlock(help_text='Enter the heading', required=False)), ('subheading', wagtail.blocks.RichTextBlock(help_text='Enter the subheading', required=False)), ('text', wagtail.blocks.RichTextBlock(help_text='Enter the text', required=False)), ('button', wagtail.blocks.StructBlock([('text', wagtail.blocks.RichTextBlock(help_text='Enter the button value', required=False)), ('link', wagtail.blocks.URLBlock(help_text='Enter the url of this button', required=False)), ('bg_color', wagtail.blocks.ChoiceBlock(choices=[('darkblue', 'Dark Blue'), ('green', 'Green'), ('white', 'White')], help_text='Choose a button type', required=False))], help_text='Enter the button', required=False)), ('contact_us', wagtail.blocks.BooleanBlock(help_text='Check if you want to show contact us button', required=False)), ('bg_color', wagtail.blocks.ChoiceBlock(choices=[('darkblue', 'Dark Blue'), ('green', 'Green'), ('white', 'White'), ('gray', 'Gray')], required=False))]))], blank=True, null=True),
        ),
    ]
