# Generated by Django 5.0.7 on 2024-07-28 17:30

import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0093_uploadedfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.StreamField([('hero', wagtail.blocks.StreamBlock([('text', wagtail.blocks.RichTextBlock(help_text='Enter Description for your hero section', required=True)), ('image', wagtail.images.blocks.ImageChooserBlock(help_text='Choose a image related to your bussiness', required=True))])), ('about', wagtail.blocks.RichTextBlock(help_text='Tell about yourself and the history of your business growth', required=True)), ('highlight_text', wagtail.blocks.RichTextBlock(help_text='The text inside this section will displayed with a different background in home page. For example you can mention what you will buy as a buyer or what you sell as a seller.', required=False)), ('guid', wagtail.blocks.StreamBlock([('text', wagtail.blocks.RichTextBlock(help_text='Make it clear, tell the customers or sellers about the rules, if and else', required=True)), ('steps', wagtail.blocks.StructBlock([('step', wagtail.blocks.StreamBlock([('step', wagtail.blocks.TextBlock(help_text='Enter the name of the space', required=True)), ('image', wagtail.images.blocks.ImageChooserBlock(help_text='Enter a image related to this step (it can be a symbol or a emoji transparented for better output)', required=True)), ('text', wagtail.blocks.TextBlock(help_text='What in this step costs for consumer', required=True))]))]))])), ('advantages', wagtail.blocks.StreamBlock([('bonus', wagtail.blocks.StreamBlock([('text', wagtail.blocks.RichTextBlock(help_text='why customer have to choose you? explain with dotted and short phrases', required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(help_text='Choose a related image', required=False))])), ('text', wagtail.blocks.RichTextBlock(help_text='This text will shown under bonus section', required=False))])), ('contact_us_text', wagtail.blocks.RichTextBlock(help_text='This text will displayed at contact form', required=False)), ('last_speech', wagtail.blocks.RichTextBlock(help_text='If there is things that you have to mention about it', required=False))])),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
