# Generated by Django 5.0.10 on 2024-12-11 23:42

import wagtail.blocks
import wagtail.contrib.table_block.blocks
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("compare", "0002_alter_comparepage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comparepage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    (
                        "heading",
                        wagtail.blocks.RichTextBlock(form_classname="full title"),
                    ),
                    (
                        "subheading",
                        wagtail.blocks.RichTextBlock(form_classname="full title"),
                    ),
                    ("paragraph", wagtail.blocks.RichTextBlock()),
                    (
                        "table",
                        wagtail.contrib.table_block.blocks.TableBlock(
                            table_options={
                                "autoColumnSize": False,
                                "colHeaders": False,
                                "editor": "text",
                                "height": 108,
                                "languege": "en",
                                "minSpareRows": 0,
                                "renderer": "text",
                                "rowHeaders": False,
                                "startCols": 3,
                                "startRows": 6,
                                "stretchH": "all",
                            }
                        ),
                    ),
                    (
                        "highlight_box",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "heading",
                                    wagtail.blocks.RichTextBlock(
                                        help_text="Enter the heading", required=False
                                    ),
                                ),
                                (
                                    "subheading",
                                    wagtail.blocks.RichTextBlock(
                                        help_text="Enter the subheading", required=False
                                    ),
                                ),
                                (
                                    "text",
                                    wagtail.blocks.RichTextBlock(
                                        help_text="Enter the text", required=False
                                    ),
                                ),
                                (
                                    "button",
                                    wagtail.blocks.StructBlock(
                                        [
                                            (
                                                "text",
                                                wagtail.blocks.RichTextBlock(
                                                    help_text="Enter the button value",
                                                    required=False,
                                                ),
                                            ),
                                            (
                                                "link",
                                                wagtail.blocks.URLBlock(
                                                    help_text="Enter the url of this button",
                                                    required=False,
                                                ),
                                            ),
                                            (
                                                "bg_color",
                                                wagtail.blocks.ChoiceBlock(
                                                    choices=[
                                                        ("darkblue", "Dark Blue"),
                                                        ("green", "Green"),
                                                        ("white", "White"),
                                                    ],
                                                    help_text="Choose a button type",
                                                    required=False,
                                                ),
                                            ),
                                        ],
                                        help_text="Enter the button",
                                        required=False,
                                    ),
                                ),
                                (
                                    "contact_us",
                                    wagtail.blocks.BooleanBlock(
                                        help_text="Check if you want to show contact us button",
                                        required=False,
                                    ),
                                ),
                                (
                                    "bg_color",
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ("darkblue", "Dark Blue"),
                                            ("green", "Green"),
                                            ("white", "White"),
                                            ("gray", "Gray"),
                                        ],
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "button",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "text",
                                    wagtail.blocks.RichTextBlock(
                                        help_text="Enter the button value",
                                        required=False,
                                    ),
                                ),
                                (
                                    "link",
                                    wagtail.blocks.URLBlock(
                                        help_text="Enter the url of this button",
                                        required=False,
                                    ),
                                ),
                                (
                                    "bg_color",
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ("darkblue", "Dark Blue"),
                                            ("green", "Green"),
                                            ("white", "White"),
                                        ],
                                        help_text="Choose a button type",
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    ),
                ],
                blank=True,
                null=True,
            ),
        ),
    ]
