# Generated by Django 5.0.7 on 2024-07-28 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_sitesettings_site'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='headermenu',
            name='setting',
        ),
    ]
