# Generated by Django 5.0.7 on 2024-07-28 10:08

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_headermenu_setting'),
    ]

    operations = [
        migrations.AddField(
            model_name='headermenu',
            name='setting',
            field=modelcluster.fields.ParentalKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='header_menu', to='base.sitesettings'),
            preserve_default=False,
        ),
    ]
