# Generated by Django 5.0.7 on 2024-07-28 10:18

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_sitesettings_company_claims_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('company_number', models.CharField(default='09123456789', help_text='Enter your company phone number', max_length=15)),
                ('motivate_text', models.CharField(default='09123456789', help_text='Something to make user motivated like : Get A Cash Offer Today', max_length=250)),
                ('motivate_url', models.URLField(default='Enter motivation url', help_text='When user cliked on motivate text, where shall he go? enter the url.')),
                ('company_name', models.CharField(default='09123456789', help_text="Enter name of your company (it'll displayed below the logo)", max_length=200)),
                ('company_claims', models.CharField(default='09123456789', help_text='Enter your company claims', max_length=300)),
                ('setting', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_setting', to='base.sitesettings')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
