# Generated by Django 5.0.7 on 2024-07-28 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_mainsetting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainsetting',
            name='setting',
        ),
    ]
