# Generated by Django 5.0.7 on 2024-07-28 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_mainsetting_setting'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='company_claims',
            field=models.CharField(default='09123456789', help_text='Enter your company claims', max_length=300),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='company_name',
            field=models.CharField(default='09123456789', help_text="Enter name of your company (it'll displayed below the logo)", max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='company_number',
            field=models.CharField(default='09123456789', help_text='Enter your company phone number', max_length=15),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='motivate_text',
            field=models.CharField(default='09123456789', help_text='Something to make user motivated like : Get A Cash Offer Today', max_length=250),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='motivate_url',
            field=models.URLField(default='Enter motivation url', help_text='When user cliked on motivate text, where shall he go? enter the url.'),
        ),
        migrations.DeleteModel(
            name='MainSetting',
        ),
    ]
