# Generated by Django 5.0.7 on 2024-07-28 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_sitesettings_company_claims_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headermenu',
            name='url',
            field=models.CharField(max_length=100),
        ),
    ]
