# Generated by Django 5.0.7 on 2024-07-28 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_headermenu_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='motivate_url',
            field=models.CharField(default='Enter motivation url', help_text='When user cliked on motivate text, where shall he go? enter the url.', max_length=100),
        ),
    ]
