# Generated by Django 5.0.10 on 2024-12-11 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0012_footer"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="company_logo",
            field=models.ImageField(
                blank=True,
                help_text="Enter your company image picture",
                null=True,
                upload_to="",
            ),
        ),
    ]
